# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
project_name: stalk
before:
  hooks:
    - make completion manual
builds:
  - id: linux
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - riscv64
    ldflags:
      - -X 'main.Version={{ .Version }}'
      - -X 'main.Hash={{ .FullCommit }}'
  - id: mac
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X 'github.com/AppleGamer22/stalk/cmd.Version={{ .Version }}'
      - -X 'github.com/AppleGamer22/stalk/cmd.Hash={{ .FullCommit }}'
  - id: windows
    goos:
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X 'github.com/AppleGamer22/stalk/cmd.Version={{ .Version }}'
      - -X 'github.com/AppleGamer22/stalk/cmd.Hash={{ .FullCommit }}'
archives:
  - id: unix
    builds:
    - linux
    - mac
    replacements:
      darwin: mac
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - stalk.bash
      - stalk.fish
      - stalk.zsh
      - stalk.1
  - id: windows
    builds:
      - windows
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - stalk.ps1
      - stalk.1
nfpms:
  - package_name: stalk
    vendor: AppleGamer22
    maintainer: Omri Bornstein <omribor@gmail.com>
    homepage: https://github.com/AppleGamer22/stalk
    license: GPL-3.0
    description: Cross-platform file watcher.
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds:
      - linux
    dependencies:
      - dbus
    formats:
      - apk
      - deb
      - rpm
    contents:
      - src: stalk.1
        dst: /usr/share/man/man1/stalk.1
      - src: stalk.bash
        dst: /usr/share/bash-completion/completions/stalk
      - src: stalk.fish
        dst: /usr/share/fish/completions/stalk.fish
      - src: stalk.zsh
        dst: /usr/share/zsh/site-functions/_stalk
changelog:
  use: github
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^chore'
    - typo
    - Merge pull request
    - Merge remote-tracking branch
    - Merge branch
    - go mod tidy
  groups:
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Other work
      order: 999
release:
  github:
    owner: AppleGamer22
    name: stalk
  discussion_category_name: General
  footer: |
    ## Installation
    ### Arch Linux Distributions
    * [`yay`](https://github.com/Jguer/yay):
    ```bash
    yay -S stalk-bin
    ```
    * [`paru`](https://github.com/morganamilo/paru):
    ```bash
    paru -S stalk-bin
    ```

    ### macOS
    * [Homebrew Tap](https://github.com/AppleGamer22/homebrew-stalk):
    ```bash
    brew install AppleGamer22/tap/stalk
    ```
  prerelease: auto
aurs:
  - homepage: https://github.com/AppleGamer22/stalk
    description: Cross-platform file watcher.
    license: GPL3
    maintainers:
      - Omri Bornstein <omribor@gmail.com>
    contributors:
      - Omri Bornstein <omribor@gmail.com>
    private_key: "{{ .Env.AUR_SSH_PRIVATE_KEY }}"
    git_url: ssh://aur@aur.archlinux.org/stalk-bin.git
    depends:
      - dbus
    optdepends:
      - bash
      - fish
      - zsh
    package: |
      install -Dm755 stalk "${pkgdir}/usr/bin/stalk"
      install -Dm644 stalk.1 "${pkgdir}/usr/share/man/man1/stalk.1"
      install -Dm644 stalk.bash "${pkgdir}/usr/share/bash-completion/completions/stalk"
      install -Dm644 stalk.fish "${pkgdir}/usr/share/fish/vendor_completions.d/stalk.fish"
      install -Dm644 stalk.zsh "${pkgdir}/usr/share/zsh/site-functions/_stalk"
    commit_author:
      name: Omri Bornstein
      email: omribor@gmail.com
brews:
  - tap:
      owner: AppleGamer22
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    download_strategy: CurlDownloadStrategy
    commit_author:
      name: Omri Bornstein
      email: omribor@gmail.com
    homepage: https://github.com/AppleGamer22/stalk
    description: Cross-platform file watcher.
    license: GPL-3.0
    install: |
      bin.install "stalk"
      man1.install "stalk.1"
      bash_completion.install "stalk.bash" => "stalk"
      fish_completion.install "stalk.fish"
      zsh_completion.install "stalk.zsh" => "_stalk"