name: Test
on:
  pull_request:
    types:
      - opened
      - closed
      - reopened
  workflow_dispatch:
    inputs: {}
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{matrix.os}}
    steps:
      - name: Pull Source Code
        uses: actions/checkout@v3.4.0
      - name: Set-up Go
        uses: actions/setup-go@v3.5.0
        with:
          go-version: stable
      - name: Test
        run: make test
